name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      id: login-docker
      run: docker login -e ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build, test tag, and push image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-docker.outputs.registry }}
        REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker run -t $REGISTRY/$REPOSITORY:$IMAGE_TAG go test .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Logout of Docker Hub
      if: always()
      run: docker logout ${{ steps.login-docker.outputs.registry }}

